main(/)
	***@+F1(100)
	@+L1(100)
	@+L2(100)
	***/'Введите числа через пробел: '>C
	***/F1<C
	5=k
	X=L1
	*printf(a/) /'\n'>C
	
	*** *div_mul_test(a, b/c)
	
	?(a#c)3
	
	P2 /'Ok!\n'>C ?=4
	P3 /'Error: a#c\n'>C
	P4 
	P5 **
	
	
	
div_mul_test(a, b/c)
	a/b=c a;b=d b*c=c c+d=c
	**
	
	
	
str2ns(F1, q/d, a)
	Oi Oj
	P1 ?(i>=Q1)4
  		F1i=c
  		?(j=2)3
  		?(c#' ')2 a=d Oa Di Dj ?=1
  P2
      *c2n(c/b)
      a*q+b=a
      Di ?=1
  P3	/'ERROR: Введено больше двух чисел\n'>C Oa Od
  P4
	**
